<a href="https://colab.research.google.com/github/HerculesVirus/Natural-Language-Processing/blob/master/Working_code/Document_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practis Purpose

In [ ]:
import pandas as pd

In [ ]:
Dummy = ['milk bread bread bread : grocery',
       'bread milk milk bread : grocery',
       'milk milk milk bread bread bread bread : grocery',
       'cat cat cat dog dog bark : pets',
       'dog dog cat bark new new : pets',
       'cat dog cat dog new cat : pets']

In [ ]:
x , y = [] , []
for doc in Dummy:
  i, l = doc.split(':')
  x.append(i.strip())
  y.append(l.strip())


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
matrix_x = vec.fit_transform(x)

In [ ]:
matrix_x

<6x6 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [ ]:
matrix_x.toarray() 

array([[0, 3, 0, 0, 1, 0],
       [0, 2, 0, 0, 2, 0],
       [0, 4, 0, 0, 3, 0],
       [1, 0, 3, 2, 0, 0],
       [1, 0, 1, 2, 0, 2],
       [0, 0, 3, 2, 0, 1]])

In [ ]:
vec.vocabulary_

{'bark': 0, 'bread': 1, 'cat': 2, 'dog': 3, 'milk': 4, 'new': 5}

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(matrix_x, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
knn.fit(matrix_x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
knn.fit(matrix_x[:5],y[:5])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
knn.predict(matrix_x[5])

array(['pets'], dtype='<U7')

In [ ]:
knn.predict_proba(matrix_x[5])

array([[0.33333333, 0.66666667]])

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
nbc = MultinomialNB()

In [ ]:
nbc.fit(matrix_x[:5],y[:5])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
nbc.fit(matrix_x[:5],y[:5])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
nbc.predict(matrix_x[5])

array(['pets'], dtype='<U7')

In [ ]:
nbc.predict_proba(matrix_x[5])

array([[6.34470873e-05, 9.99936553e-01]])

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dtc = DecisionTreeClassifier(max_depth=3)

In [ ]:
dtc.fit(matrix_x[:5],y[:5])

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
dtc.predict(matrix_x[5])

array(['grocery'], dtype='<U7')

In [ ]:
dtc.predict_proba(matrix_x[5])

array([[1., 0.]])

In [ ]:
from sklearn.linear_model import SGDClassifier

In [ ]:
linear = SGDClassifier()

In [ ]:
linear.fit(matrix_x[:5],y[:5])

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
linear.predict(matrix_x[5])

array(['pets'], dtype='<U7')

#PART-2

In [ ]:
knn = KNeighborsClassifier(n_neighbors= 3 , algorithm= 'kd_tree' ,weights= 'distance')

In [ ]:
nb = MultinomialNB(alpha = 1.0, class_prior= [0.7, 0.3])

In [ ]:
dt = DecisionTreeClassifier(max_depth = 2)


In [ ]:
ln = SGDClassifier(max_iter=1000)

In [ ]:
#/content/drive/MyDrive/8th Semester/NLP/Document Classification (Categorization)/Dataset/Dataset.csv'
corpus = open('/content/drive/MyDrive/8th Semester/NLP/Document Classification (Categorization)/Dataset/badges.data.txt').read()
docs = corpus.split('\n')
print(docs[:5])
print("length of Docs : ",len(docs))
X, y = [], [] 
for doc in docs:
    l = doc[:1]
    i = doc[2:]
    X.append(i.strip())
    y.append(l.strip())
print("X : ",X)
print("Y : ",y[284])
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer(max_df = 17,max_features= 15)
matrix_X = vec.fit_transform(X)
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(max_depth = 56)
dt.fit(matrix_X[:284], y[:284])
#predicted labels of the last four documents
print(dt.predict(matrix_X[284:])) 
#prediction probability of the two labels for each of the last four documents
print(dt.predict_proba(matrix_X[284:])) 

['+ Naoki Abe', '- Myriam Abramson', '+ David W. Aha', '+ Kamal M. Ali', '- Eric Allender']
length of Docs :  294
X :  ['Naoki Abe', 'Myriam Abramson', 'David W. Aha', 'Kamal M. Ali', 'Eric Allender', 'Dana Angluin', 'Chidanand Apte', 'Minoru Asada', 'Lars Asker', 'Javed Aslam', 'Haralabos Athanassiou', 'Jose L. Balcazar', 'Timothy P. Barber', 'Michael W. Barley', 'Cristina Baroglio', 'Peter Bartlett', 'Eric Baum', 'Welton Becket', 'Shai Ben-David', 'George Berg', 'Neil Berkman', 'Malini Bhandaru', 'Bir Bhanu', 'Reinhard Blasig', 'Avrim Blum', 'Anselm Blumer', 'Justin Boyan', 'Carla E. Brodley', 'Nader Bshouty', 'Wray Buntine', 'Andrey Burago', 'Tom Bylander', 'Bill Byrne', 'Claire Cardie', 'Richard A. Caruana', 'John Case', 'Jason Catlett', 'Nicolo Cesa-Bianchi', 'Philip Chan', 'Mark Changizi', 'Pang-Chieh Chen', 'Zhixiang Chen', 'Wan P. Chiang', 'Steve A. Chien', 'Jeffery Clouse', 'William Cohen', 'David Cohn', 'Clare Bates Congdon', 'Antoine Cornuejols', 'Mark W. Craven', 'Robert P.

In [ ]:
corpus = open('/content/drive/MyDrive/8th Semester/NLP/Document Classification (Categorization)/Dataset/badges.data.txt').read()
docs = corpus.split('\n')
docs


['+ Naoki Abe',
 '- Myriam Abramson',
 '+ David W. Aha',
 '+ Kamal M. Ali',
 '- Eric Allender',
 '+ Dana Angluin',
 '- Chidanand Apte',
 '+ Minoru Asada',
 '+ Lars Asker',
 '+ Javed Aslam',
 '+ Haralabos Athanassiou',
 '+ Jose L. Balcazar',
 '+ Timothy P. Barber',
 '+ Michael W. Barley',
 '- Cristina Baroglio',
 '+ Peter Bartlett',
 '- Eric Baum',
 '+ Welton Becket',
 '- Shai Ben-David',
 '+ George Berg',
 '+ Neil Berkman',
 '+ Malini Bhandaru',
 '+ Bir Bhanu',
 '+ Reinhard Blasig',
 '- Avrim Blum',
 '- Anselm Blumer',
 '+ Justin Boyan',
 '+ Carla E. Brodley',
 '+ Nader Bshouty',
 '- Wray Buntine',
 '- Andrey Burago',
 '+ Tom Bylander',
 '+ Bill Byrne',
 '- Claire Cardie',
 '+ Richard A. Caruana',
 '+ John Case',
 '+ Jason Catlett',
 '+ Nicolo Cesa-Bianchi',
 '- Philip Chan',
 '+ Mark Changizi',
 '+ Pang-Chieh Chen',
 '- Zhixiang Chen',
 '+ Wan P. Chiang',
 '- Steve A. Chien',
 '+ Jeffery Clouse',
 '+ William Cohen',
 '+ David Cohn',
 '- Clare Bates Congdon',
 '- Antoine Cornuejols',
 